import Statistics from "pages/AccountPages/Account/components/Statistics";
;

export const RouteName = {
  LOGIN: "/login",
  Transactions: '/transactions',
  Coins: '/coins',
  Referral: '/referral',
  Boost: '/boost',
  Matches: '/matches',
  Reports: '/reports',
  Statistics:"/statistics",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  ACCOUNT: "/users",
  CREATE_ACCOUNT: "/accounts/create",
  EDIT_ACCOUNT: "/accounts/:id/edit",
  ACCOUNT_DETAIL: "/accounts/:id",
  FLEET_MODEL: "/fleet-models",
  CREATE_FLEET_MODEL: "/fleet-models/create",
  EDIT_FLEET_MODEL: "/fleet-models/:id/edit",
  FLEET_MODEL_DETAIL: "/fleet-models/:id",
  COUNTRY: "/countries",
  CREATE_COUNTRY: "/countries/create",
  EDIT_COUNTRY: "/countries/:id/edit",
  COUNTRY_DETAIL: "/countries/:id",
  TRIP_DETAIL: "/trip/:id",
  CITY: "/cities",
  CREATE_CITY: "/cities/create",
  EDIT_CITY: "/cities/:id/edit",
  DRIVER: "/drivers",
  CREATE_DRIVER: "/drivers/create",
  EDIT_DRIVER: "/drivers/:id/edit",
  DRIVER_DETAIL: "/drivers/:id",
  DRIVER_WALLET: "/driver-wallets",
  EDIT_DRIVER_WALLET: "/driver-wallets/:id/edit",
  FLEET: "/fleets",
  EDIT_FLEET: "/fleets/:id/edit",
  FLEET_DETAIL: "/fleets/:id",
  DISPATCHER_DASHBOARD: "/dispatchers/dashboard",
  DISPATCHER: "/dispatchers",
  NEWS_BROADCAST: "/new-broadcast",
  NEWS: "/news",
  PROMO_CODE: "/promo-codes",
  RATING: "/ratings",
  TRIP: "/trips",
  USER: "/users",
  FINANCE: "/finances",
  SETTING: "/settings",
  EDIT_TRIP: "/trips/:id/edit"
};
